TaxReturn/TaxReturn/Controllers/AccountTransactionController.cs
using System.Web.Mvc;
using PagedList;
using TaxReturn.Core;
using TaxReturn.Extensions;

namespace TaxReturn.Controllers
{
    public class AccountTransactionController : Controller
    {
        private readonly IQueryAccountTransaction _queryAccountTransaction;

        public AccountTransactionController(IQueryAccountTransaction queryAccountTransaction)
        {
            _queryAccountTransaction = queryAccountTransaction;
        }
     
        public ActionResult Index(int? page)
        {
            var results = _queryAccountTransaction.GetAll().ToAccountTransactionViewModels();

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            
            return View(results.ToPagedList(pageNumber, pageSize));
        }
    }
}

TaxReturn/TaxReturn/Controllers/FileUploadController.cs
using System.Data.Entity.Infrastructure;
using System.Web;
using System.Web.Mvc;
using TaxReturn.Core;
using TaxReturn.Models;

namespace TaxReturn.Controllers
{
    public class FileUploadController : Controller
    {
        private readonly IUploadFileContentService _fileUploadContentService;
        public FileUploadController(IUploadFileContentService fileUploadFileContentService)
        {
            _fileUploadContentService = fileUploadFileContentService;

        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Upload(HttpPostedFileBase upload)
        {
            if(upload == null || upload.FileName.EndsWith(".csv"))
                ModelState.AddModelError("Missing file", "Please upload file");
            try
            {
                if (ModelState.IsValid)
                {
                  
                    var result =  _fileUploadContentService.UploadFile(upload.InputStream);
                    var viewModel = new FileUploadResultsViewModel(result);
                    return View("UploadResults", viewModel);
                }
            }
            catch (RetryLimitExceededException exception)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                //log error
            }
            return View("Index");
        }
         
    }
}

TaxReturn/TaxReturn/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Tax Return Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Upload File", "Index", "FileUpload", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("View All Transactions", "Index", "AccountTransaction")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>